### PR TITLE
Active each terminal with a keyboard shortcut

### LINKED ISSUE #37: [Feature] Add keyboard shortcut to open each terminal
For example, you can define `cmd-1` to open first terminal, `cmd-2` to open second terminal, etc

It's a great productivity boost for heavy keyboard users.

### PR DESCRIPTION
**Pull request by gutenye**
fix #37

### CODE REVIEW

**Comment by gutenye** [comment]
screen shot 2017-03-18 at 8 18 51 pm

**Comment by gutenye** [comment]
It's empty

**Comment by gutenye** [comment]
screen shot 2017-03-18 at 8 20 31 pm

**Comment by Fred-Barclay** [comment]
Awesome, thanks. 
I've got the same behavior on Linux, where the keybinder resolver sees `alt-shift-1` as `alt-!`. This means the following doesn't work in the keymaps:
```
'alt-shift-1': 'termination:active-1'
```
Does it work anyway on macOS? 
If not, what are some keybindings that you think would be appropriate? Not having a mac myself I'd definitely appreciate your input since I don't want to cause a conflict between Atom, termination, and the OS itself. :smile:

Cheers!

**Comment by gutenye** [comment]
How about theses:

````
'alt-!': 'termination:active-1'
'alt-@': 'termination:active-2'
'alt-#': 'termination:active-3'
'alt-$': 'termination:active-4'
````

It works and they are not taken by Atom and the OS itself.

**Comment by Fred-Barclay** [comment]
I thought about that (I meant to say so earlier... sorry!) but my concern is that, when a user is looking at the keybinding hints, it won't be immediately obvious what alt-! actually is. What do you think? Would it be confusing?

**Comment by gutenye** [comment]
Other keybindings:

```
Cmd-1                # used by atom, panel:show-item-1
Cmd-Shift-3      # used by macOS, take a screenshot
Ctrl-1                  # used by atom, tree-view:open-selected-entry-in-panel-1
Ctrl-Shift-1         # empty, display as Ctrl-!
```

Not much options available here.

I still recommend use `alt-shift-1`.  1) it will match other keybindings used by termination like `alt-shift-j`.  2) we can put  `alt-shift-1` in README, so that it will not confuse the users. (Most users will read the README, and begin to use it, they may not know it is actually displayed as `alt-!` in atom, like me in first place)

**Comment by Fred-Barclay** [comment]
I think you're right. :) I'll do a bit more testing and then let's get this merged! :smile:

**Comment by Fred-Barclay** [comment]
Merged - thanks!
https://github.com/Fred-Barclay/Termination/commit/a4519bf7e3d04daff517541e2011c0d2be7d54e4

**Comment by the-j0k3r** [comment]
Isnt this redundant when you can use `termination:next` `termination:previous` anyway? + theres no limitation to only 4 terminals

https://github.com/bus-stop/Termination/blob/5097f007fc9a1289a6240858f1fff2f465dbc914/keymaps/termination.cson#L3-L4

https://github.com/bus-stop/Termination/blob/5097f007fc9a1289a6240858f1fff2f465dbc914/keymaps/termination.cson#L17-L18

Works a treat
generic

**Pull request merged**
